### ISSUE TITLE
Why is gog version only in discord?

### ISSUE THREAD

**Issue by reserveword** [dextercd/Noita-Disable-Mod-Restrictions#1]
I can't open that discord link, how can I join the channel?

**Comment by dextercd** [comment]
I didn't make the ~~Discord~~ GOG version. It's there because the person who made it posted it there.

You should be able to join the Discord via this link: https://discord.gg/SZtrP2r

Link to post: https://discord.com/channels/453998283174576133/1096171782865698857

The GOG version of Noita was updated recently so it might no longer work. If you can't get it working then you should contact the author of the GOG version of the mod.
